#!/usr/bin/env bash

# Code is generated by ucloud-model, DO NOT EDIT IT.

ucloud-model sdk apis --lang python3 --type public --template ${U_MODEL_HOME}/providers/python/templates/clients.tpl --output ./ucloud/client.py
ucloud-model sdk apis --lang python3 --type public --template ${U_MODEL_HOME}/providers/python/templates/docs.tpl --output ./docs/services.rst


mkdir -p ./ucloud/services/pathx/schemas
touch ./ucloud/services/pathx/__init__.py
touch ./ucloud/services/pathx/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product PathX --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/pathx/schemas/apis.py
ucloud-model sdk apis --lang python3 --product PathX --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/pathx/schemas/models.py
ucloud-model sdk apis --lang python3 --product PathX --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/pathx/client.py

mkdir -p ./ucloud/services/stepflow/schemas
touch ./ucloud/services/stepflow/__init__.py
touch ./ucloud/services/stepflow/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product StepFlow --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/stepflow/schemas/apis.py
ucloud-model sdk apis --lang python3 --product StepFlow --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/stepflow/schemas/models.py
ucloud-model sdk apis --lang python3 --product StepFlow --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/stepflow/client.py

mkdir -p ./ucloud/services/uaccount/schemas
touch ./ucloud/services/uaccount/__init__.py
touch ./ucloud/services/uaccount/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product UAccount --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/uaccount/schemas/apis.py
ucloud-model sdk apis --lang python3 --product UAccount --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/uaccount/schemas/models.py
ucloud-model sdk apis --lang python3 --product UAccount --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/uaccount/client.py

mkdir -p ./ucloud/services/udb/schemas
touch ./ucloud/services/udb/__init__.py
touch ./ucloud/services/udb/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product UDB --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/udb/schemas/apis.py
ucloud-model sdk apis --lang python3 --product UDB --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/udb/schemas/models.py
ucloud-model sdk apis --lang python3 --product UDB --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/udb/client.py

mkdir -p ./ucloud/services/udpn/schemas
touch ./ucloud/services/udpn/__init__.py
touch ./ucloud/services/udpn/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product UDPN --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/udpn/schemas/apis.py
ucloud-model sdk apis --lang python3 --product UDPN --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/udpn/schemas/models.py
ucloud-model sdk apis --lang python3 --product UDPN --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/udpn/client.py

mkdir -p ./ucloud/services/udisk/schemas
touch ./ucloud/services/udisk/__init__.py
touch ./ucloud/services/udisk/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product UDisk --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/udisk/schemas/apis.py
ucloud-model sdk apis --lang python3 --product UDisk --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/udisk/schemas/models.py
ucloud-model sdk apis --lang python3 --product UDisk --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/udisk/client.py

mkdir -p ./ucloud/services/uhost/schemas
touch ./ucloud/services/uhost/__init__.py
touch ./ucloud/services/uhost/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product UHost --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/uhost/schemas/apis.py
ucloud-model sdk apis --lang python3 --product UHost --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/uhost/schemas/models.py
ucloud-model sdk apis --lang python3 --product UHost --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/uhost/client.py

mkdir -p ./ucloud/services/ulb/schemas
touch ./ucloud/services/ulb/__init__.py
touch ./ucloud/services/ulb/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product ULB --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/ulb/schemas/apis.py
ucloud-model sdk apis --lang python3 --product ULB --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/ulb/schemas/models.py
ucloud-model sdk apis --lang python3 --product ULB --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/ulb/client.py

mkdir -p ./ucloud/services/umem/schemas
touch ./ucloud/services/umem/__init__.py
touch ./ucloud/services/umem/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product UMem --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/umem/schemas/apis.py
ucloud-model sdk apis --lang python3 --product UMem --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/umem/schemas/models.py
ucloud-model sdk apis --lang python3 --product UMem --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/umem/client.py

mkdir -p ./ucloud/services/unet/schemas
touch ./ucloud/services/unet/__init__.py
touch ./ucloud/services/unet/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product UNet --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/unet/schemas/apis.py
ucloud-model sdk apis --lang python3 --product UNet --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/unet/schemas/models.py
ucloud-model sdk apis --lang python3 --product UNet --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/unet/client.py

mkdir -p ./ucloud/services/uphost/schemas
touch ./ucloud/services/uphost/__init__.py
touch ./ucloud/services/uphost/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product UPHost --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/uphost/schemas/apis.py
ucloud-model sdk apis --lang python3 --product UPHost --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/uphost/schemas/models.py
ucloud-model sdk apis --lang python3 --product UPHost --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/uphost/client.py

mkdir -p ./ucloud/services/usms/schemas
touch ./ucloud/services/usms/__init__.py
touch ./ucloud/services/usms/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product USMS --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/usms/schemas/apis.py
ucloud-model sdk apis --lang python3 --product USMS --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/usms/schemas/models.py
ucloud-model sdk apis --lang python3 --product USMS --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/usms/client.py

mkdir -p ./ucloud/services/vpc/schemas
touch ./ucloud/services/vpc/__init__.py
touch ./ucloud/services/vpc/schemas/__init__.py
ucloud-model sdk apis --lang python3 --product VPC --type public --template ${U_MODEL_HOME}/providers/python/templates/schema.tpl --output ./ucloud/services/vpc/schemas/apis.py
ucloud-model sdk apis --lang python3 --product VPC --type public --template ${U_MODEL_HOME}/providers/python/templates/model.tpl --output ./ucloud/services/vpc/schemas/models.py
ucloud-model sdk apis --lang python3 --product VPC --type public --template ${U_MODEL_HOME}/providers/python/templates/client.tpl --output ./ucloud/services/vpc/client.py

